config/routes.rb
BeaugolaisIntranet::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  scope '/manage' do
    resources :users do
      put :reset, on: :member
      get :reset, on: :member
      put :new_password, on: :collection
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.is_a?(Admin)
      can :manage, :all
    end

    if user && user.is_a?(Customer)
      can :manage, :all
    end
  end
end

app/models/admin.rb
class Admin < User
  def self.model_name
    User.model_name
  end
end

app/models/customer.rb
class Customer < User
  def self.model_name
    User.model_name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_token_authenticatable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  validates :firstname,
            presence: true

  validates :lastname,
            presence: true

  validates :type,
            presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  acts_as_token_authentication_handler_for User
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  skip_before_filter :verify_authenticity_token, :only => :create

  private
    def sign_up_params
      params.require(:user).permit(:lastname, :firstname, :type, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:lastname, :firstname, :type, :email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :html, :json
  def new
    if request.format.to_s == 'application/json'
      if current_user.nil?
        respond_to do |format|
          format.json do
            render json: {  }, status: 401 and return
          end
        end
      end
    end
    super
  end

  def create
    respond_to do |format|
      format.html do
        cookies[:login_attempts] ||= 0

        if params[:user][:email].blank? || params[:user][:password].blank?
          cookies[:login_attempts] = cookies[:login_attempts].to_i + 1
        end

        if verify_recaptcha
          cookies[:login_attempts] = 0
          resource = warden.authenticate!(scope: resource_name, recall: 'sessions#failure')
          sign_in_and_redirect(resource_name, resource)
        else
          redirect_to new_user_session_path
        end
      end

      format.json do
        resource = warden.authenticate!(scope: resource_name, recall: 'sessions#failure')
        sign_in_and_redirect(resource_name, resource)
      end
    end
  end

  def sign_in_and_redirect(resource_or_scope, resource=nil)
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(scope, resource) unless warden.user(scope) == resource

    respond_to do |format|
      format.html do
        redirect_to stored_location_for(scope) || after_sign_in_path_for(resource)
      end

      format.json do
        render json: { success: resource } and return
      end
    end
  end

  def failure
    respond_to do |format|
      format.html do
        redirect_to new_user_session_path
      end

      format.json do
        render json: {  }, status: 401 and return
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json

  before_action :authenticate_user!, except: [:new, :create, :new_password]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :reset]

  def index
    authorize! :read, User
    @users = User.all
    respond_with(@users)
  end

  def new
    authorize! :create, User
    @user = User.new
    respond_with(@user)
  end

  def edit
    authorize! :update, User
  end

  def create
    authorize! :create, User
    @user = User.new user_params

    respond_to do |format|
      format.html do
        if @user.save
          redirect_to users_path
        else
          render 'new'
        end
      end

      format.json do
        if @user.save
          render json: @user, status: 200 and return
        else
          render json: @user, status: 400 and return
        end
      end
    end
  end

  def update
    authorize! :update, User
    @user.update(user_params)
    respond_to do |format|
      format.html do
        if @user.save
          redirect_to users_path
        else
          render 'edit'
        end
      end

      format.json do
        if @user.save
          render json: @user, status: 200 and return
        else
          render json: @user, status: 400 and return
        end
      end
    end
  end

  def new_password
    current_user.reset_password!(params[:user][:password], params[:user][:password_confirmation])
  end

  def reset
    authorize! :update, User
    respond_to do |format|
      format.html do
        @user.send_reset_password_instructions
        redirect_to users_path
      end

      format.json do
        if @user.send_reset_password_instructions
          render json: @user, status: 200 and return
        else
          render json: @user, status: 400 and return
        end
      end
    end
  end

  def destroy
    authorize! :destroy, User
    @user.destroy
    respond_with(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/confirmable/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.slim
doctype html
html
  head
    title Beaujolais Intranet
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:300,700', media: 'all'
    = yield(:head)
    = csrf_meta_tags
  body
    nav.navbar.navbar-default role="navigation"
      .container-fluid
        .navbar-header
          a.navbar-brand href="/" Beaujolais Intranet
        .collapse.navbar-collapse.navbar-right
          ul.nav.navbar-nav
            li
              = link_to 'Déconnexion', destroy_session_path(:user), method: :delete
    .container
      = yield

    = javascript_include_tag 'application'
    = yield(:scripts)

app/views/pages/home.html.slim
.container
  .row-fluid
    .col-xs-12.text-center
      = image_tag 'logo_2.png'
      h1 Bienvenue dans votre interface client !
      = link_to 'Consulter les membres', users_path, class: 'btn btn-success'

app/views/users/_form.html.slim
= simple_form_for @user, as: :user do |f|
  .form-inputs
    .form-group
      = f.input :firstname, required: true, input_html: { class: 'form-control' }, autofocus: true
    .form-group
      = f.input :lastname, required: true, input_html: { class: 'form-control' }
    .form-group
      = f.input :email, required: true, input_html: { class: 'form-control' }
    .form-group
      = f.input :password, required: true, input_html: { class: 'form-control' }
    .form-group
      = f.input :password_confirmation, required: true, input_html: { class: 'form-control' }
    .form-group
      = f.input :type, label: 'Type', collection: [['Admin', 'Admin'], ['Client', 'Customer']], include_blank: false, input_html: { class: 'form-control' }

  .form-actions
    = f.button :submit, 'Valider', class: 'btn btn-success'

app/views/users/edit.html.slim
h1 Édition d'un utilisateur

= render 'form'

app/views/users/index.html.slim
.row
  .col-sm-12
    h1 Gestion des utilisateurs
.row
  .col-sm-12
    table.table.table-bordered
      thead
        th Nom
        th Prénom
        th Statut
        th Créé
        th Actions

      - @users.each do |user|
        tr
          td= user.firstname
          td= user.lastname
          td= user.type
          td= user.created_at.to_date.to_s
          td
            = link_to 'Editer', edit_user_path(user), class: 'btn btn-success'
            = link_to 'Supprimer', user_path(user), method: :delete, class: 'btn btn-danger'
            = link_to 'Réinitialiser le mot de passe', reset_user_path(user), class: 'btn btn-danger'
  .col-sm-12
    = link_to 'Créer un utilisateur', new_user_url, class: 'btn btn-success'

app/views/users/new.html.slim
h1 Créer un utilisateur

= render 'form'